#!/bin/bash
# GitHub快速部署指南

echo "=========================================="
echo "🚀 智能旅行规划Agent - GitHub部署"
echo "=========================================="
echo ""
echo "项目已准备就绪！请按以下步骤完成部署："
echo ""
echo "【方法1: 使用GitHub网页界面（最简单）】"
echo "1. 访问 https://github.com/new"
echo "2. 填写仓库名: travel-agent"
echo "3. 选择 Public（公开）"
echo "4. 不要勾选 'Initialize this repository with a README'"
echo "5. 点击 'Create repository'"
echo "6. 复制页面显示的以下命令（在 '…or push an existing repository' 部分）："
echo ""
echo "   git remote add origin https://github.com/你的用户名/travel-agent.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "7. 在项目目录中运行这些命令"
echo ""
echo "【方法2: 使用GitHub CLI】"
echo "运行: gh repo create travel-agent --public --source=. --push"
echo ""
echo "【方法3: 使用部署脚本】"
echo "如果你有GitHub Token，运行: ./deploy.sh YOUR_TOKEN"
echo ""
echo "=========================================="
echo "项目文件已准备就绪，等待推送..."
echo "=========================================="
